#!/usr/bin/env bash
# Script to install nginx on web-01 server
sudo apt-get update
sudo rm /var/lib/dpkg/lock-frontend
sudo apt-get -y install nginx
sudo apt-get upgrade -y
sudo ufw allow 'Nginx HTTP'
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=mN_jYKCTEwU&t=10s;\n\t}' /etc/nginx/sites-available/default
sudo service nginx start
