#!/usr/bin/env bash
# Script to install nginx on web-01 server
rewrite_me="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
error404="\n\\terror_page 404 /404.html;\n\tlocation = /var/www/html/404.html {\n\t\tinternal;\n\t}"
PATTERN="#error_page 404 /404.html;"


sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "30i $rewrite_me" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "47i\ $PATTERN$error404" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
