#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y update
apt-get -y install haproxy

printf %s "
backend web-servers
        balance roundrobin
        option forwardfor
        server 491327-web-01 34.207.211.122:80 check
        server 491327-web-02 100.25.143.0:80 check
frontend haproxy_balancer
         bind *:80
         mode http
         default_backend web-servers
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
