#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it.
# mysqldump -u root -p "$1" tyrell_corp > backup.sql && tar -cvf "$(date +%d-%m-%Y).tar.gz" backup.sql
# mysqldump --all-databases -u root --password="$1" > backup.sql && tar -czvf "$(date +%d-%m-%Y).tar.gz" backup.sql
mysqldump --all-databases -u root --password="$1" > backup.sql
archive=$(date +'%d-%m-%Y')
tar -czvf "$archive.tar.gz" backup.sql
