#!/usr/bin/env bash
# Script to fix what’s keeping Ubuntu container’s Nginx installation from listening on port 80
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
