#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes.
hours=0
minutes=1
echo "Hour: $hours"
while [[ $hours -le 12 || $minutes -le 59 ]];
do
    if [[ $minutes -lt 60 && $hours -lt 12 ]];
    then
        echo "$minutes"
        minutes=$((minutes+1))

    elif [ $minutes -eq 60 ];
    then
        hours=$((hours+1))
        minutes=1
        echo "Hour: $hours"

    elif [ $hours -eq 12 ];
    then
        break
    fi
done
